// ui-v2/src/components/deployments/deployments-filter-presets-bar.tsx
import type { ColumnFiltersState } from "@tanstack/react-table";
import { useEffect, useRef, useState } from "react";
import type { components } from "@/api/prefect";
import { SaveFilterDialog } from "@/components/runs/save-filter-dialog";
import { Button } from "@/components/ui/button";
import { DeleteConfirmationDialog } from "@/components/ui/delete-confirmation-dialog";
import { Icon } from "@/components/ui/icons";
import { cn } from "@/utils";
import {
	areDeploymentFiltersEqual,
	type DeploymentSavedFilterValues,
	type SavedDeploymentFilter,
	useDeploymentsSavedFilters,
} from "./use-deployments-saved-filters";

export type DeploymentsFilterPresetsBarProps = {
	columnFilters: ColumnFiltersState;
	sort: components["schemas"]["DeploymentSort"];
	onColumnFiltersChange: (columnFilters: ColumnFiltersState) => void;
	onSortChange: (sort: components["schemas"]["DeploymentSort"]) => void;
	onClearFilters?: () => void;
	className?: string;
};

export const DeploymentsFilterPresetsBar = ({
	columnFilters,
	sort,
	onColumnFiltersChange,
	onSortChange,
	onClearFilters,
	className,
}: DeploymentsFilterPresetsBarProps) => {
	const [isSaveDialogOpen, setIsSaveDialogOpen] = useState(false);
	const [filterToDelete, setFilterToDelete] =
		useState<SavedDeploymentFilter | null>(null);
	const [selectedPresetId, setSelectedPresetId] = useState<string | null>(null);
	const [renamingId, setRenamingId] = useState<string | null>(null);
	const [draftName, setDraftName] = useState("");
	const ignoreRenameBlurRef = useRef(false);
	const renameInputRef = useRef<HTMLInputElement>(null);

	const {
		savedFilters,
		saveFilter,
		updateFilter,
		deleteFilter,
		findMatchingFilter,
	} = useDeploymentsSavedFilters();

	const flowOrDeploymentName = (columnFilters.find(
		(filter) => filter.id === "flowOrDeploymentName",
	)?.value ?? "") as string;
	const tags = (columnFilters.find((filter) => filter.id === "tags")?.value ??
		[]) as string[];

	const currentFilterValues: DeploymentSavedFilterValues = {
		flowOrDeploymentName: flowOrDeploymentName || undefined,
		tags: tags.length ? tags : undefined,
		sort,
	};

	const matchingFilter = findMatchingFilter(currentFilterValues);
	const hasActiveFilters =
		Boolean(flowOrDeploymentName.trim()) || tags.length > 0;
	const isAllActive = !hasActiveFilters;

	useEffect(() => {
		if (matchingFilter) {
			setSelectedPresetId(matchingFilter.id);
		}
	}, [matchingFilter]);

	useEffect(() => {
		if (!renamingId) {
			return;
		}
		renameInputRef.current?.focus();
		renameInputRef.current?.select();
	}, [renamingId]);

	const selectedPreset = hasActiveFilters
		? savedFilters.find((preset) => preset.id === selectedPresetId)
		: undefined;
	const isDirty = Boolean(
		selectedPreset &&
			!areDeploymentFiltersEqual(selectedPreset.filters, currentFilterValues),
	);

	const handleSelectAll = () => {
		setSelectedPresetId(null);
		if (onClearFilters) {
			onClearFilters();
		} else {
			onColumnFiltersChange([]);
		}
	};

	const handleSelectPreset = (preset: SavedDeploymentFilter) => {
		setSelectedPresetId(preset.id);
		const newFilters: ColumnFiltersState = [];
		if (preset.filters.flowOrDeploymentName) {
			newFilters.push({
				id: "flowOrDeploymentName",
				value: preset.filters.flowOrDeploymentName,
			});
		}
		if (preset.filters.tags && preset.filters.tags.length > 0) {
			newFilters.push({
				id: "tags",
				value: preset.filters.tags,
			});
		}
		onColumnFiltersChange(newFilters);
		if (preset.filters.sort) {
			onSortChange(preset.filters.sort);
		}
	};

	const handleSave = (name: string) => {
		saveFilter({
			name,
			filters: currentFilterValues,
		});
	};

	const handleUpdate = () => {
		if (!selectedPreset) {
			return;
		}
		updateFilter(selectedPreset.id, { filters: currentFilterValues });
	};

	const startRename = (preset: SavedDeploymentFilter) => {
		ignoreRenameBlurRef.current = false;
		setRenamingId(preset.id);
		setDraftName(preset.name);
	};

	const cancelRename = () => {
		setRenamingId(null);
		setDraftName("");
	};

	const commitRename = (preset: SavedDeploymentFilter) => {
		if (ignoreRenameBlurRef.current) {
			ignoreRenameBlurRef.current = false;
			return;
		}
		const name = draftName.trim();
		if (name && name !== preset.name) {
			updateFilter(preset.id, { name });
		}
		cancelRename();
	};

	const hasPresets = savedFilters.length > 0;
	const showSave = hasActiveFilters && !matchingFilter;

	if (!hasPresets && !showSave) {
		return null;
	}

	return (
		<>
			<div
				className={cn(
					"flex items-center gap-1.5 overflow-x-auto py-1 scrollbar-none",
					className,
				)}
			>
				{hasPresets && (
					<>
						<span className="text-xs font-medium text-muted-foreground shrink-0 mr-1 flex items-center gap-1">
							<Icon id="SlidersVertical" className="size-3" />
							Presets:
						</span>

						<Button
							variant={isAllActive ? "secondary" : "ghost"}
							size="sm"
							className={cn(
								"h-7 rounded-full px-3 text-xs font-medium shrink-0",
								isAllActive &&
									"bg-secondary text-secondary-foreground font-semibold shadow-xs",
							)}
							onClick={handleSelectAll}
						>
							All
						</Button>
					</>
				)}

				{savedFilters.map((preset) => {
					const isActive = selectedPreset?.id === preset.id;
					const isDirtyPreset = isActive && isDirty;
					const isRenaming = renamingId === preset.id;
					return (
						<div
							key={preset.id}
							className={cn(
								"group inline-flex items-center rounded-full border border-border text-xs transition-colors shrink-0",
								isActive
									? "bg-secondary text-secondary-foreground font-semibold border-secondary-foreground/20 shadow-xs"
									: "bg-background text-muted-foreground hover:bg-muted hover:text-foreground",
							)}
						>
							{isRenaming ? (
								<input
									ref={renameInputRef}
									aria-label={`Rename preset ${preset.name}`}
									autoComplete="off"
									className="h-7 min-w-24 rounded-full bg-transparent px-3 text-xs outline-none"
									maxLength={100}
									size={Math.max(draftName.length, 8)}
									value={draftName}
									onBlur={() => commitRename(preset)}
									onChange={(event) => setDraftName(event.target.value)}
									onClick={(event) => event.stopPropagation()}
									onKeyDown={(event) => {
										if (event.key === "Enter") {
											event.preventDefault();
											commitRename(preset);
										}
										if (event.key === "Escape") {
											event.preventDefault();
											ignoreRenameBlurRef.current = true;
											cancelRename();
										}
									}}
								/>
							) : (
								<>
									<button
										type="button"
										className="px-3 py-1 text-xs focus:outline-hidden cursor-pointer"
										onClick={() => handleSelectPreset(preset)}
									>
										{isDirtyPreset ? `${preset.name} •` : preset.name}
									</button>
									<button
										type="button"
										aria-label={`Rename preset ${preset.name}`}
										className="inline-flex items-center justify-center overflow-hidden w-0 p-0 opacity-0 text-muted-foreground/60 hover:text-foreground focus:outline-hidden cursor-pointer group-hover:w-4 group-hover:opacity-100 focus-visible:w-4 focus-visible:opacity-100 [@media(hover:none)]:w-4 [@media(hover:none)]:opacity-100"
										onClick={(event) => {
											event.stopPropagation();
											startRename(preset);
										}}
									>
										<Icon id="Pencil" className="size-3" />
									</button>
									<button
										type="button"
										aria-label={`Delete preset ${preset.name}`}
										className="pr-2 pl-0.5 py-1 text-muted-foreground/60 hover:text-destructive focus:outline-hidden cursor-pointer"
										onClick={(event) => {
											event.stopPropagation();
											setFilterToDelete(preset);
										}}
									>
										<Icon id="X" className="size-3" />
									</button>
								</>
							)}
						</div>
					);
				})}

				{isDirty && (
					<Button
						variant="secondary"
						size="sm"
						className="h-7 rounded-full px-2.5 text-xs font-medium shrink-0"
						onClick={handleUpdate}
					>
						Update
					</Button>
				)}

				{hasActiveFilters && !matchingFilter && (
					<Button
						variant="outline"
						size="sm"
						className="h-7 rounded-full px-2.5 text-xs font-normal border-dashed gap-1 shrink-0 text-muted-foreground hover:text-foreground"
						onClick={() => setIsSaveDialogOpen(true)}
					>
						<Icon id="Plus" className="size-3" />
						Save filter
					</Button>
				)}
			</div>

			<SaveFilterDialog
				open={isSaveDialogOpen}
				onOpenChange={setIsSaveDialogOpen}
				onSave={handleSave}
			/>

			<DeleteConfirmationDialog
				isOpen={Boolean(filterToDelete)}
				title="Delete filter preset"
				description={`Are you sure you want to delete "${filterToDelete?.name}"?`}
				onConfirm={() => {
					if (filterToDelete) {
						deleteFilter(filterToDelete.id);
						setFilterToDelete(null);
					}
				}}
				onClose={() => setFilterToDelete(null)}
			/>
		</>
	);
};

// ui/src/components/DeploymentsFilterPresetsBar.vue
<template>
  <div v-if="hasPresets || showSave" class="deployments-filter-presets-bar">
    <template v-if="hasPresets">
      <span class="deployments-filter-presets-bar__label">
        Presets:
      </span>

      <p-button
        small
        class="deployments-filter-presets-bar__pill"
        :class="{ 'deployments-filter-presets-bar__pill--active': isAllActive }"
        @click="selectAll"
      >
        All
      </p-button>

      <div
        v-for="preset in savedFilters"
        :key="preset.id"
        class="deployments-filter-presets-bar__preset"
        :class="{ 'deployments-filter-presets-bar__preset--active': selectedPreset?.id === preset.id }"
      >
        <input
          v-if="renamingId === preset.id"
          :aria-label="`Rename preset ${preset.name}`"
          class="deployments-filter-presets-bar__preset-input"
          maxlength="100"
          :size="Math.max(draftName.length, 8)"
          :value="draftName"
          @blur="commitRename(preset)"
          @click.stop
          @input="onDraftInput"
          @keydown.enter.prevent="commitRename(preset)"
          @keydown.escape.prevent="cancelRename"
        >
        <template v-else>
          <button type="button" class="deployments-filter-presets-bar__preset-name" @click="selectPreset(preset)">
            {{ selectedPreset?.id === preset.id && isDirty ? `${preset.name} •` : preset.name }}
          </button>
          <button
            type="button"
            class="deployments-filter-presets-bar__preset-rename"
            :aria-label="`Rename preset ${preset.name}`"
            @click.stop="startRename(preset)"
          >
            ✎
          </button>
          <button
            type="button"
            class="deployments-filter-presets-bar__preset-delete"
            :aria-label="`Delete preset ${preset.name}`"
            @click.stop="filterToDelete = preset"
          >
            ×
          </button>
        </template>
      </div>
    </template>

    <p-button v-if="isDirty" small class="deployments-filter-presets-bar__pill" @click="updateSelected">
      Update
    </p-button>

    <p-button v-if="showSave" small class="deployments-filter-presets-bar__save" @click="showSaveModal = true">
      Save filter
    </p-button>
  </div>

  <p-modal v-model:show-modal="showSaveModal" title="Save filter preset">
    <p-label label="Name">
      <p-text-input v-model="newFilterName" placeholder="e.g. Alpha Services" />
    </p-label>

    <template #actions>
      <p-button primary :disabled="!newFilterName.trim()" @click="saveCurrent">
        Save
      </p-button>
    </template>
  </p-modal>

  <p-modal v-model:show-modal="showDeleteModal" title="Delete filter preset">
    <p>
      Are you sure you want to delete "{{ filterToDelete?.name }}"?
    </p>

    <template #actions>
      <p-button danger @click="confirmDelete">
        Delete
      </p-button>
    </template>
  </p-modal>
</template>

<script lang="ts" setup>
  import { useDeploymentsPaginationFilterFromRoute } from '@prefecthq/prefect-ui-library'
  import { computed, nextTick, ref, watch } from 'vue'
  import {
    areDeploymentFiltersEqual,
    type DeploymentSavedFilterValues,
    type SavedDeploymentFilter,
    useDeploymentsSavedFilters
  } from '@/compositions/useDeploymentsSavedFilters'

  const { filter, clear } = useDeploymentsPaginationFilterFromRoute()
  const { savedFilters, saveFilter, updateFilter, deleteFilter, findMatchingFilter } = useDeploymentsSavedFilters()

  const selectedPresetId = ref<string | null>(null)
  const showSaveModal = ref(false)
  const newFilterName = ref('')
  const filterToDelete = ref<SavedDeploymentFilter | null>(null)
  const renamingId = ref<string | null>(null)
  const draftName = ref('')
  let ignoreRenameBlur = false

  const currentFilterValues = computed<DeploymentSavedFilterValues>(() => {
    const tags = filter.deployments.tags.name
    return {
      flowOrDeploymentName: filter.deployments.flowOrDeploymentNameLike === ''
        ? undefined
        : filter.deployments.flowOrDeploymentNameLike,
      tags: tags?.length ? [...tags] : undefined,
      sort: filter.sort,
    }
  })

  const matchingFilter = computed(() => findMatchingFilter(currentFilterValues.value))
  const hasActiveFilters = computed(() => {
    return Boolean(currentFilterValues.value.flowOrDeploymentName?.trim()) || Boolean(currentFilterValues.value.tags?.length)
  })
  const isAllActive = computed(() => !hasActiveFilters.value)
  const hasPresets = computed(() => savedFilters.value.length > 0)
  const showSave = computed(() => hasActiveFilters.value && !matchingFilter.value)

  watch(matchingFilter, (match) => {
    if (match) {
      selectedPresetId.value = match.id
    }
  }, { immediate: true })

  const selectedPreset = computed(() => {
    if (!hasActiveFilters.value) {
      return undefined
    }
    return savedFilters.value.find((preset) => preset.id === selectedPresetId.value)
  })

  const isDirty = computed(() => {
    return Boolean(
      selectedPreset.value &&
        !areDeploymentFiltersEqual(selectedPreset.value.filters, currentFilterValues.value),
    )
  })

  const showDeleteModal = computed({
    get() {
      return filterToDelete.value !== null
    },
    set(value: boolean) {
      if (!value) {
        filterToDelete.value = null
      }
    },
  })

  function applyFilters(values: DeploymentSavedFilterValues): void {
    filter.deployments.flowOrDeploymentNameLike = values.flowOrDeploymentName
    filter.deployments.tags.name = values.tags?.length ? [...values.tags] : undefined
    if (values.sort) {
      filter.sort = values.sort
    }
    filter.page = 1
  }

  function selectAll(): void {
    selectedPresetId.value = null
    clear()
  }

  function selectPreset(preset: SavedDeploymentFilter): void {
    selectedPresetId.value = preset.id
    applyFilters(preset.filters)
  }

  function updateSelected(): void {
    if (!selectedPreset.value) {
      return
    }
    updateFilter(selectedPreset.value.id, { filters: currentFilterValues.value })
  }

  function startRename(preset: SavedDeploymentFilter): void {
    ignoreRenameBlur = false
    renamingId.value = preset.id
    draftName.value = preset.name
    void nextTick(() => {
      const input = document.querySelector(
        ".deployments-filter-presets-bar__preset-input",
      ) as HTMLInputElement | null
      input?.focus()
      input?.select()
    })
  }

  function onDraftInput(event: Event): void {
    draftName.value = (event.target as HTMLInputElement).value
  }

  function cancelRename(): void {
    ignoreRenameBlur = true
    renamingId.value = null
    draftName.value = ''
  }

  function commitRename(preset: SavedDeploymentFilter): void {
    if (ignoreRenameBlur) {
      ignoreRenameBlur = false
      return
    }
    const name = draftName.value.trim()
    if (name && name !== preset.name) {
      updateFilter(preset.id, { name })
    }
    renamingId.value = null
    draftName.value = ''
  }

  function saveCurrent(): void {
    const name = newFilterName.value.trim()
    if (!name) {
      return
    }
    saveFilter({
      name,
      filters: currentFilterValues.value,
    })
    newFilterName.value = ''
    showSaveModal.value = false
  }

  function confirmDelete(): void {
    if (!filterToDelete.value) {
      return
    }
    deleteFilter(filterToDelete.value.id)
    filterToDelete.value = null
  }
</script>

<style>
.deployments-filter-presets-bar { @apply
  flex
  items-center
  gap-1.5
  overflow-x-auto
  py-1
  mb-3
}

.deployments-filter-presets-bar__label { @apply
  text-xs
  font-medium
  text-subdued
  shrink-0
  mr-1
}

.deployments-filter-presets-bar__pill { @apply
  shrink-0
}

.deployments-filter-presets-bar__pill--active { @apply
  font-semibold
}

.deployments-filter-presets-bar__preset { @apply
  inline-flex
  items-center
  rounded-full
  border
  text-xs
  shrink-0
}

.deployments-filter-presets-bar__preset--active { @apply
  font-semibold
}

.deployments-filter-presets-bar__preset-name { @apply
  px-3
  py-1
  text-xs
  cursor-pointer
}

.deployments-filter-presets-bar__preset-rename { @apply
  inline-flex
  items-center
  justify-center
  overflow-hidden
  w-0
  p-0
  text-subdued
  cursor-pointer
  opacity-0
}

.deployments-filter-presets-bar__preset:hover .deployments-filter-presets-bar__preset-rename,
.deployments-filter-presets-bar__preset-rename:focus-visible { @apply
  w-4
  opacity-100
}

@media (hover: none) {
  .deployments-filter-presets-bar__preset-rename { @apply
    w-4
    opacity-100
  }
}

.deployments-filter-presets-bar__preset-input { @apply
  h-7
  min-w-24
  rounded-full
  bg-transparent
  px-3
  text-xs
  outline-none
}

.deployments-filter-presets-bar__preset-delete { @apply
  pr-2
  pl-0.5
  py-1
  text-subdued
  cursor-pointer
}

.deployments-filter-presets-bar__save { @apply
  shrink-0
}
</style>
